### ISSUE TITLE
Add automatic tests 🕑 20h

### ISSUE THREAD

**Issue by RodionRybakov** [stacc-dasso/Javascript-Adapter#23]

**Comment by marlondumas** [comment]
I wonder what's the status of this task -- has anything progressed?

**Comment by MarkPeshkov** [comment]
I am dealing with it. Still struggling with log file. Tests are too quick and log have no time to appear so fast. But I will solve this problem within couple days.

**Comment by liinaanette** [comment]
I cleaned up the log file - now the log will not show the get recs event (because it was always the same and appeared too many times). No you can only look at the last line in the log file to assert that the event was recorded.
